# -*- coding: utf-8 -*-
"""Copy of Copy of CNN (5).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10aa_IxttTn1Obtj-8KKoK89pV3kJ10PD
"""

import cv2
from glob import glob
import pathlib
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt


from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense,Conv3D,MaxPool3D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

anim_path=pathlib.Path(r"C:\Users\user\Desktop\CNN_Project\Flask\Animals\data")

zero_list=list(anim_path.glob("butterfly/*.jpg"))          # *-shows all #(malignant/*)- shows all files inside the malignant folder
one_list=list(anim_path.glob("koala/*.jpg"))
two_list=list(anim_path.glob("lion/*.jpg"))
three_list=list(anim_path.glob("panda/*.jpg"))
four_list=list(anim_path.glob("seahorse/*.jpg"))
five_list=list(anim_path.glob("snake/*.jpg"))
six_list=list(anim_path.glob("starfish/*.jpg"))
seven_list=list(anim_path.glob("wolf/*.jpg"))
eight_list=list(anim_path.glob("woodpecker/*.jpg"))
nine_list=list(anim_path.glob("zebra/*.jpg"))

len(zero_list),len(one_list),len(two_list),len(three_list),len(four_list),len(five_list),len(six_list),len(seven_list),len(eight_list),len(nine_list)

anim_dict={"butterfly":zero_list,
              "koala":one_list,
              "lion":two_list,
              "panda":three_list,
              "seahorse":four_list,
              "snake":five_list,
              "starfish":six_list,
              "wolf":seven_list,
              "woodpecker":eight_list,
              "zebra":nine_list,
             }
anim_class={"butterfly":0,
              "koala":1,
               "lion":2,
               "panda":3,
               "seahorse":4,
               "snake":5,
               "starfish":6,
               "wolf":7,
               "woodpecker":8,
               "zebra":9,
              }

x=[]
y=[]

for i in anim_dict:
  anim_name=i
  anim_path_list=anim_dict[anim_name]
  for path in anim_path_list:
    img=cv2.imread(str(path))
    img=cv2.resize(img,(224,224))
    img=img/255
    x.append(img)
    cls=anim_class[anim_name]
    y.append(cls)

len(x)

x=np.array(x)
y=np.array(y)

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.75,random_state=1)

len(xtrain),len(ytrain),len(xtest),len(ytest)

xtrain.shape

xtrain.shape,xtest.shape

from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2

base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),include_top=False,weights='imagenet')

print("[INFO] summary for base model...")
print(base_model.summary())

from tensorflow.keras.layers import MaxPooling2D
from keras.layers.core import Dropout
from tensorflow.keras.models import Model
headModel= base_model.output
headModel= MaxPooling2D(pool_size=(2,2))(headModel)
headModel= Flatten(name="flatten")(headModel)
headModel= Dense(32, activation="relu")(headModel)
headModel= Dropout(0.2)(headModel)
headModel= Dense(10, activation="softmax")(headModel)
model= Model(inputs=base_model.input, outputs=headModel)
for layer in base_model.layers:
  layer.trainable= False

from tensorflow.keras.optimizers import Adam
print("[INFO] compiling model....")
opt= Adam(lr=1e-4)
model.compile(loss="sparse_categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
print("[INFO] training head....")
model_hist=model.fit(xtrain,ytrain,epochs=10,validation_data=(xtest,ytest),batch_size=180)

model.save("weight.h5")

#model_hist=model.fit(xtrain,ytrain,epochs=5,validation_data=(xtest,ytest),batch_size=180)


# from tensorflow.keras.preprocessing import image
# # testing the model
# def testing_image(image_directory):
#     test_image = image.load_img(image_directory, target_size = (224, 224))
#     test_image = image.img_to_array(test_image)
#     test_image = np.expand_dims(test_image, axis = 0)
#     test_image = test_image/255
#     result = model.predict(x= test_image)
#     print(result)
#     if np.argmax(result)  == 0:
#       prediction = 'butterfly'
#     elif np.argmax(result)  == 1:
#       prediction = 'koala'
#     elif np.argmax(result)  == 2:
#       prediction = 'lion'
#     elif np.argmax(result)  == 3:
#       prediction = 'panda'
#     elif np.argmax(result)  == 4:
#       prediction = 'seahorse'
#     elif np.argmax(result)  == 5:
#       prediction = 'snake'
#     elif np.argmax(result)  == 6:
#       prediction = 'starfish'
#     elif np.argmax(result)  == 7:
#       prediction = 'wolf'
#     elif np.argmax(result)  == 8:
#       prediction = 'woodpecker'
#     else:
#       prediction = 'zebra'
#     return prediction

# print(testing_image('/content/drive/MyDrive/Python/Deep_Learning/CNN/Animal_classification/data/starfish/174c7f3ea1 - Copy.jpg'))

# from sklearn.metrics import  confusion_matrix

# Y_pred = model.predict_generator(xtest)

# y_pred = np.argmax(Y_pred, axis=1)

# print('Confusion Matrix')

# c=confusion_matrix(ytest, Y_pred)
# #cm = confusion_matrix(np.where(ytest), Y_pred)

# import keras
# keras.__version__

